config/routes.rb
Rails.application.routes.draw do
  get 'carts/index'

  get 'carts/edit'

  get 'carts/update'

  get 'categories/index'
  get 'categories/new'
  get 'categories/show'
  get 'categories/edit'
  get 'products/index'
  get 'products/new'
  get 'products/show'
  get 'products/edit'
  get    'password_resets/new'
  get    'password_resets/edit'
  get    'sessions/new'
  get    'register'  => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :products
  resources :categories
  resources :carts
  root 'static_pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    validates :subtotal, presence: true
    validates :tax, presence: true
    validates :shipping, presence: true
    validates :total, presence: true
  
    enum status: [ :cancelled, :in_progress, :completed, :invoiced ]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.all
  end

  def edit
    @cart = Cart.find(params[:id])
    @statuses = Cart.statuses
  end

  def update
    @cart = Cart.find(params[:id])
    @statuses = Cart.statuses
    if @cart.update_attributes(cart_params)
      redirect_to carts_path, notice: "The order has been created."
    else
      render "edit"
    end
  end

private
  def cart_params
    params.require(:order).permit(:subtotal, :tax, :shipping, :total, :status)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<div class="container">
  <h3>Editing Order No <%= @cart.id %></h3>
  <hr />
  <% if @cart.errors.any? %>
    <div class="alert alert-danger">
       <h2>
          <%= pluralize(@user.errors.count, "error")%>
              prohibited this user from being saved:  
          </h2>
          <ul>
            <%= @cart.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>   
    </div>
  <% end %>

  <%= form_for @cart do |f| %>
    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.label :subtotal, class: "control-label" %>
        <%= f.number_field :subtotal, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.label :tax %>
        <%= f.number_field :tax, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.label :shipping %>
        <%= f.number_field :shipping, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.label :total %>
        <%= f.number_field :total, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.label :status %>
        <%= f.select :status, options_for_select(@statuses.collect { |s| [s[0].humanize, s[0]] }, selected: @cart.status), {} , class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 form-group">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/carts/index.html.erb
<div class="container">
  <h3>Orders</h3>
  <table class="table table-bordered table-striped">
    <tr>
      <th>Order No</th>
      <th>Subtotal</th>
      <th>Tax</th>
      <th>Shipping</th>
      <th>Total</th>
      <th>Order Status</th>
      <td>&nbsp;</td>
    </tr>
    <% @carts.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= number_to_currency order.subtotal %></td>
        <td><%= number_to_currency order.tax %></td>
        <td><%= number_to_currency order.shipping %></td>
        <td><%= number_to_currency order.total %></td>
        <td><%= order.status.humanize %></td>
        <td><%= link_to "Edit", edit_cart_path(order), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>