config/routes.rb
Rails.application.routes.draw do
  get 'carts/index'

  get 'carts/edit'

  get 'carts/update'

  get 'categories/index'
  get 'categories/new'
  get 'categories/show'
  get 'categories/edit'
  get 'products/index'
  get 'products/new'
  get 'products/show'
  get 'products/edit'
  get    'password_resets/new'
  get    'password_resets/edit'
  get    'sessions/new'
  get    'register'  => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :products
  resources :categories
  resources :carts
  root 'static_pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :admin_user,     only: [:destroy, :edit, :update, :new]
  
  
  def index
      products_controller = ProductsController.new
      products_controller.request = request
      products_controller.response = response
      products_controller.index
      @categories = Category.paginate(page: params[:page])
  end

  def new
      @category = Category.new
  end

  def show
      @category = Category.find(params[:id])
      
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @category }
      end
  end

  def edit
      @category = Category.find(params[:id])
  end
  
  def create
      @category = Category.new(params[:category].permit(:name, :description))
      @category.save
      redirect_to categories_path
  end
  
  def update
      if @category = Category.find(params[:id])
          @category.update_attributes(params[:category].permit(:name, :description))
      end
      redirect_to categories_path
  end
  
  def destroy
      if @category = Category.find(params[:id])
          @category.delete
      end
      redirect_to categories_path
  end
  
  private
  
  # Confirms an admin user.
  def admin_user
    users_controller = UsersController.new
    users_controller.request = request
    users_controller.response = response
    users_controller.admin_user
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Edit Category ID #<%= @category.id %></h1>
<%= link_to "Back to Categories", category_path %>

<%= form_for @category do |f| %>
  <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
  </p>
  <p>
      <%= f.label :description %>
      <%= f.text_field :description %>
  </p>
  <p>
      <%= f.submit %>
      <%= link_to "Delete", category_path(@category), :method=>:delete %>
  </p>
<% end %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<ul>
  <% @categories.each do |p| %>
    <li>
      <%= link_to p.name, p %>
      <%= p.description %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>Create Product</h1>

<%= form_for @category, url: categories_path do |f| %>
  <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
  </p>
  <p>
      <%= f.label :description %>
      <%= f.text_field :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/categories/show.html.erb
<%= link_to "Back to categories", categories_path %>

<h3><%= @category.name %></h3>
<p><%= @category.description %></p>

<% Product.where(category_id: @category.id).each do |product| %>
<li> <%= product.name %> </li>
<% end %>