config/routes.rb
Rails.application.routes.draw do
  get 'carts/index'

  get 'carts/edit'

  get 'carts/update'

  get 'categories/index'
  get 'categories/new'
  get 'categories/show'
  get 'categories/edit'
  get 'products/index'
  get 'products/new'
  get 'products/show'
  get 'products/edit'
  get    'password_resets/new'
  get    'password_resets/edit'
  get    'sessions/new'
  get    'register'  => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :products
  resources :categories
  resources :carts
  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<!-- Start Footer -->
		<table border="1" width="100%" style="border-width: 0px" cellspacing="0" cellpadding="0">
			<tr>
				<td style="border-bottom:4px solid #000000; " bgcolor="#808080">
				<font face="Yu Gothic UI Semilight">copyright © 2016, All rights 
				reserved.<br>
				This footer is temporary and will be updated before submission.</font></td>
			</tr>
		</table>
		<!-- End Footer -->

app/views/layouts/_header.html.erb
<!-- Start Header -->
		<table>
			<tr>
				<td>
				<table>
					<tr>
						<td class="header_bar" colspan="2">
						<table>
							<tr>
								<td class="header_bar_content">
								<%=image_tag("cart.png", alt: "Shopping Cart")%>
								<%= link_to "Shopping Cart", carts_path %> <b>| </b><% if logged_in? %> <%= link_to "My Account", current_user %> <b>| </b><%= link_to "Log out", logout_path, method: "delete" %><% else %><%= link_to "Log in", login_path %> <b>|</b> 
								<%= link_to "Sign Up!", register_path %> <% end %></td>
							</tr>
						</table>
						</td>
					</tr>
					<tr>
						<td class="logo">
						<%=image_tag("logo.png", alt: "Buzzit")%></td>
						<td class="logo_side">
&nbsp;</td>
					</tr>
					<tr>
						<td class="nav_bar" colspan="2">
						<table>
							<tr>
								<td class="nav_bar_holders">
								<table>
									<tr>
										<td>
										&nbsp;<%=image_tag("department_list.png", alt: "List All Departments")%></td>
										<td class="all_departments">
										&nbsp;<%= link_to "Shop all departments", categories_path %></td>
									</tr>
								</table>
								</td>
								<td>&nbsp;</td>
								<td class="nav_bar_holders">
								<table>
									<tr>
										<td>
										<input type="text" name="T1" size="20"></td>
										<td class="search_button">
										Search</td>
									</tr>
								</table>
								</td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		<!-- End Header -->

app/views/layouts/_space.html.erb
				<table>
					<tr>
						<td>&nbsp;</td>
					</tr>
				</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    	<%= csrf_meta_tags %>
  	</head>
<body>

<table>
	<tr>
		<td>
		
		<%= render 'layouts/header' %>
		
		<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      	<% end %>
		
		<!-- Start Content -->
		<%= yield %>
		<!-- End Content -->
		
		<%= render 'layouts/footer' %>
		</td>
	</tr>
</table>

</body>

</html>